import { useState, useEffect, useRef, useCallback, useMemo, memo } from 'react'
import { Canvas, useFrame } from '@react-three/fiber'
import { Stars, Environment } from '@react-three/drei'
import { EffectComposer, Bloom, Vignette } from '@react-three/postprocessing'
import { BlendFunction } from 'postprocessing'
import { withAudioBase } from './config/audio'
import * as THREE from 'three'

const CA = '4NBTf8PfLH4oLFnwf3knv46FY9i5oXjDxffCetXRpump'
const DEX_URL = 'https://dexscreener.com/solana/969wmqydp6mc8jel2v7tmpv5pwzwbfqzkmienne2jbfe'
const ARTISTS = ['AGENT M','BERSERK','BOBLIN','DIAMOND HANDS','ETHAN','FLO','FRANCESCO','GGILYUBSON','GRONALD','JERISCHH','LEVERAGE','MRX','SLIENT KNIGH','SYAYY','YEVINCIBLE','YURIM']
const ARTIST_TRACKS = {
'AGENT M':[{id:'AM-1',title:'BLOOD ON THE BLOCKCHAIN',src:'/assets/audio/AGENT M/BLOOD ON THE BLOCKCHAIN - AGENT MEMETIC.wav'},{id:'AM-2',title:'WHEN THE CABAL FALLS DOWN',src:'/assets/audio/AGENT M/WHEN THE CABAL FALLS DOWN - AGENT MEMETIC.wav'},{id:'AM-3',title:'MO ASS',src:'/assets/audio/AGENT M/MO ASS - AGENT MEMETIC.wav'},{id:'AM-4',title:'RUGPULL RODEO',src:'/assets/audio/AGENT M/RUGPULL RODEO - AGENT MEMETIC.wav'},{id:'AM-5',title:'DIAMOND BALL Z',src:'/assets/audio/AGENT M/DIAMOND BALL Z - AGENT MEMETIC.wav'},{id:'AM-6',title:'SINGULARITY',src:'/assets/audio/AGENT M/SINGULARITY - AGENT MEMETIC.wav'},{id:'AM-7',title:'NEW JERUSALEM',src:'/assets/audio/AGENT M/NEW JERUSALEM - AGENT MEMETIC.wav'}],
'BERSERK':[{id:'B-1',title:'2 MORE DAYS',src:'/assets/audio/BERSERK/BERSERK - 2 MORE DAYS.wav'},{id:'B-2',title:"808'S",src:"/assets/audio/BERSERK/BERSERK - 808_s.wav"},{id:'B-3',title:'ALGORYTHM',src:'/assets/audio/BERSERK/BERSERK - ALGORYTHM.wav'},{id:'B-4',title:'CH ARTIST',src:'/assets/audio/BERSERK/BERSERK - CH ARTIST.wav'},{id:'B-5',title:'CURATE',src:'/assets/audio/BERSERK/BERSERK - CURATE (Your Own World).wav'},{id:'B-6',title:'GREEN CANDLES',src:'/assets/audio/BERSERK/BERSERK - GREEN CANDLES.wav'},{id:'B-7',title:'KING OF KINGS',src:'/assets/audio/BERSERK/BERSERK - KING OF KINGS.wav'},{id:'B-8',title:'NEW JERUSALEM',src:'/assets/audio/BERSERK/BERSERK - NEW JERUSALEM.wav'},{id:'B-9',title:'NO DEVILS IN THIS HOUSE',src:'/assets/audio/BERSERK/BERSERK - NO DEVILS IN THIS HOUSE.wav'},{id:'B-10',title:'RED CANDLES',src:'/assets/audio/BERSERK/BERSERK - RED CANDLES (through the storm).wav'},{id:'B-11',title:'SIX AT THE DRIVE-THRU',src:'/assets/audio/BERSERK/BERSERK - SIX AT THE DRIVE-THRU.wav'},{id:'B-12',title:'YOU MADE IT THIS FAR',src:'/assets/audio/BERSERK/BERSERK - YOU MADE IT THIS FAR.wav'},{id:'B-13',title:'CAT-ALYST',src:'/assets/audio/BERSERK/BERSERK & ALFIE - CAT-ALYST.wav'}],
'BOBLIN':[{id:'BO-1',title:'4NBT',src:'/assets/audio/BOBLIN/BOBLIN - 4NBT.mp3'},{id:'BO-2',title:'BLOCKCHAIN KINGS',src:'/assets/audio/BOBLIN/BOBLIN - Blockchain Kings.mp3'},{id:'BO-3',title:'DIGITAL WORLD',src:'/assets/audio/BOBLIN/BOBLIN - Digital World.mp3'},{id:'BO-4',title:'TICKTOCK (FT. LEVERAGE)',src:'/assets/audio/BOBLIN/TICKTOCK.mp3'},{id:'BO-5',title:'NFT FLEX',src:'/assets/audio/BOBLIN/BOBLIN - NFT Flex.mp3'},{id:'BO-6',title:'PIXEEZUS',src:'/assets/audio/BOBLIN/BOBLIN - Pixeezus.mp3'}],
'DIAMOND HANDS':[{id:'DH-1',title:'GREEN CANDLES',src:'/assets/audio/DIAMOND HANDS/(CRYPTO DROPOUT) - DIAMOND HANDS - AI - Green Candles.wav'},{id:'DH-2',title:'HOLD YZY FOREVER',src:'/assets/audio/DIAMOND HANDS/(CRYPTO DROPOUT) - DIAMOND HANDS - AI -Hold YzY Forever.wav'},{id:'DH-3',title:'ROCKETSHIP',src:'/assets/audio/DIAMOND HANDS/(CRYPTO DROPOUT) - DIAMOND HANDS - AI - ROCKETSHIP.wav'},{id:'DH-4',title:'SIX VS SCAMMERS ANTHEM',src:'/assets/audio/DIAMOND HANDS/(CRYPTO DROPOUT) - DIAMOND HANDS - AI - SIX VS SCAMMERS ANTHEM.wav'},{id:'DH-5',title:'YOU MADE IT THIS FAR',src:'/assets/audio/DIAMOND HANDS/(CRYPTO DROPOUT) - Diamond Hands (on Verse) - YOU MADE IT THIS FAR.wav'}],
'ETHAN':[{id:'E-1',title:'ATTENTION',src:'/assets/audio/ETHAN/ETHAN - ATTENTION.wav'},{id:'E-2',title:'BUILDING 4 TRUTH',src:'/assets/audio/ETHAN/ETHAN - BUILDING 4 TRUTH.wav'}],
'FLO':[{id:'F-1',title:'I THOUGHT ABOUT SELLING YOU',src:'/assets/audio/FLO/FL0-I-thought-about-selling-you.mp3'}],
'FRANCESCO':[{id:'FR-1',title:'4NBT SOCIETY',src:'/assets/audio/FRANCESCO/FRANCESCO - 4NBT SOCIETY.mp3'},{id:'FR-2',title:'OCKYE WAYE',src:'/assets/audio/FRANCESCO/FRANCESCO - OCKYE WAYE.mp3'},{id:'FR-3',title:'ROADMAP',src:'/assets/audio/FRANCESCO/FRANCESCO - ROADMAP.mp3'},{id:'FR-4',title:'SKITZO',src:'/assets/audio/FRANCESCO/FRANCESCO - SKITZO.mp3'},{id:'FR-5',title:'SUPREME',src:'/assets/audio/FRANCESCO/FRANCESCO - SUPREME.mp3'},{id:'FR-6',title:'THE PUMP',src:'/assets/audio/FRANCESCO/FRANCESCO - THE PUMP.mp3'},{id:'FR-7',title:'TRILLION THOUGHTS',src:'/assets/audio/FRANCESCO/FRANCESCO - TRILLION THOUGHTS.mp3'},{id:'FR-8',title:'TWO MORE DAYS',src:'/assets/audio/FRANCESCO/FRANCESCO - TWO MORE DAYS.mp3'},{id:'FR-9',title:'WTF',src:'/assets/audio/FRANCESCO/FRANCESCO - WTF.mp3'},{id:'FR-10',title:'YEEZY OVER EVERYTHING (FT. ANUHAZI)',src:'/assets/audio/FRANCESCO/FRANCESCO + ANUHAZI - YEEZY OVER EVERYTHING.mp3'}],
'GGILYUBSON':[{id:'G-1',title:'ARG!',src:'/assets/audio/GGILYUBSON/GGILYUBSON - (MIXTAPE)_ARG!.wav'}],
'GRONALD':[{id:'GR-1',title:'LEPRECHAUN',src:'/assets/audio/GRONALD/LEPRECHAUN.mp3'},{id:'GR-2',title:'ALL I SEE IS RED',src:'/assets/audio/GRONALD/ALL I SEE IS RED.mp3'},{id:'GR-3',title:'BAD MAMASITA',src:'/assets/audio/GRONALD/BAD MAMASITA.mp3'},{id:'GR-4',title:'BIGGEST THREAT',src:'/assets/audio/GRONALD/BIGGEST THREAT.mp3'},{id:'GR-5',title:'BLACK BLOOD',src:'/assets/audio/GRONALD/BLACK BLOOD.mp3'},{id:'GR-6',title:'BLUE BEAR',src:'/assets/audio/GRONALD/BLUE BEAR.mp3'},{id:'GR-7',title:'BUILDERS',src:'/assets/audio/GRONALD/BUILDERS.mp3'},{id:'GR-8',title:'CHOSEN ONES',src:'/assets/audio/GRONALD/CHOSEN ONES.mp3'},{id:'GR-9',title:'DEVIL COMES OUT IN THE DARK',src:'/assets/audio/GRONALD/DEVIL COMES OUT IN THE DARK.mp3'},{id:'GR-10',title:'FADED',src:'/assets/audio/GRONALD/FADED.mp3'},{id:'GR-11',title:'GHOST',src:'/assets/audio/GRONALD/GHOST.mp3'},{id:'GR-12',title:'GRAVEYARD DONK',src:'/assets/audio/GRONALD/GRAVEYARD DONK.mp3'},{id:'GR-13',title:'HUNGER',src:'/assets/audio/GRONALD/HUNGER.mp3'},{id:'GR-14',title:'I MISS DA OLD KANYE',src:'/assets/audio/GRONALD/I MISS DA OLD KANYE.mp3'},{id:'GR-15',title:'JOHN MCAFEE',src:'/assets/audio/GRONALD/JOHN MCAFEE.mp3'},{id:'GR-16',title:'JUST LIKE THAT',src:'/assets/audio/GRONALD/JUST LIKE THAT.mp3'},{id:'GR-17',title:'LIGHTS OUT',src:'/assets/audio/GRONALD/LIGHTS OUT.mp3'},{id:'GR-18',title:'LOUD WORLD',src:'/assets/audio/GRONALD/LOUD WORLD.mp3'},{id:'GR-19',title:'LOVE DANCE',src:'/assets/audio/GRONALD/LOVE DANCE.mp3'},{id:'GR-20',title:'RAPE SEASON',src:'/assets/audio/GRONALD/RAPE SEASON.mp3'},{id:'GR-21',title:'REBELS',src:'/assets/audio/GRONALD/REBELS.mp3'},{id:'GR-22',title:'SILVER TOUCH',src:'/assets/audio/GRONALD/SILVER TOUCH.mp3'},{id:'GR-23',title:'SNAKEBITE',src:'/assets/audio/GRONALD/SNAKEBITE.mp3'},{id:'GR-24',title:'TRUMPETS',src:'/assets/audio/GRONALD/TRUMPETS.mp3'},{id:'GR-25',title:'VALET TO THE VOID',src:'/assets/audio/GRONALD/VALET TO THE VOID.mp3'},{id:'GR-26',title:'VESSELS',src:'/assets/audio/GRONALD/VESSELS.mp3'},{id:'GR-27',title:'WE KNEW',src:'/assets/audio/GRONALD/WE KNEW.mp3'},{id:'GR-28',title:"YOU CAN'T RUN",src:"/assets/audio/GRONALD/YOU CANT RUN.mp3"}],
'JERISCHH':[{id:'J-1',title:'RARE SOULS',src:'/assets/audio/JERISCHH/rare-souls.wav'},{id:'J-2',title:'SENSEI',src:'/assets/audio/JERISCHH/sensei.wav'},{id:'J-3',title:'SWITCH',src:'/assets/audio/JERISCHH/switch.wav'}],
'LEVERAGE':[{id:'L-1',title:'ALIGNMENT',src:'/assets/audio/LEVERAGE/LEVERAGE - Alignment (Saints & Signals).wav'},{id:'L-2',title:'BEAR MARKET GOSPEL',src:'/assets/audio/LEVERAGE/LEVERAGE - Bear Market Gospel.wav'},{id:'L-3',title:'BLACK TEETH',src:'/assets/audio/LEVERAGE/LEVERAGE - Black Teeth.wav'},{id:'L-4',title:'BREATHE',src:'/assets/audio/LEVERAGE/LEVERAGE - Breathe.wav'},{id:'L-5',title:'BUFFERING (INTERLUDE)',src:'/assets/audio/LEVERAGE/LEVERAGE - Buffering (Interlude).wav'},{id:'L-6',title:'BESIDE US V2',src:'/assets/audio/LEVERAGE/LEVERAGE - BESIDE US V2.wav'},{id:'L-7',title:'BESIDE US V3',src:'/assets/audio/LEVERAGE/LEVERAGE - BESIDE US V3.wav'},{id:'L-8',title:'HODL',src:'/assets/audio/LEVERAGE/LEVERAGE - HODL.wav'},{id:'L-9',title:"I'M TALKIN 'BOUT",src:"/assets/audio/LEVERAGE/LEVERAGE - i_m talkin _bout.wav"},{id:'L-10',title:'LOW VOLUME, HIGH FREQUENCY',src:'/assets/audio/LEVERAGE/LEVERAGE - Low Volume, High Frequency.wav'},{id:'L-11',title:'MEASURED MOVES',src:'/assets/audio/LEVERAGE/LEVERAGE - Measured Moves.wav'},{id:'L-12',title:'NEW DAY',src:'/assets/audio/LEVERAGE/LEVERAGE - NEW DAY.wav'},{id:'L-13',title:'REBELS',src:'/assets/audio/LEVERAGE/LEVERAGE - REBELS.wav'},{id:'L-14',title:'FUCK YOURSELF (FT. SIX)',src:'/assets/audio/LEVERAGE/LEVERAGE (Feat. Sixyeezy) - Fuck Yourself (Intro).wav'}],
'MRX':[{id:'M-1',title:'BB',src:'/assets/audio/MRX/MRX - BB.mp3'},{id:'M-2',title:'LEVELUPFOREVER',src:'/assets/audio/MRX/MRX - LEVELUPFOREVER.mp3'},{id:'M-3',title:'PROVERBS',src:'/assets/audio/MRX/MRX - PROVERBS.mp3'}],
'SLIENT KNIGH':[{id:'SK-1',title:'NEW JERUSALEM',src:'/assets/audio/SLIENT KNIGH/SLIENT KNIGH - NEW JERUSALEM.mp3'}],
'SYAYY':[{id:'S-1',title:'4NBT TIME',src:'/assets/audio/SYAYY/SYAYY - 4NBT TIME.wav'},{id:'S-2',title:'BEARS EVERYWHERE',src:'/assets/audio/SYAYY/SYAYY - BEARS EVERYWHERE.wav'},{id:'S-3',title:'BLOOD ON THE BLOCKCHAIN',src:'/assets/audio/SYAYY/SYAYY - BLOOD ON THE BLOCKCHAIN.wav'},{id:'S-4',title:'BUNDLED BUBBLES',src:'/assets/audio/SYAYY/SYAYY - BUNDLED BUBBLES.wav'},{id:'S-5',title:'CABAL FALLS DOWN',src:'/assets/audio/SYAYY/SYAYY - CABAL FALLS DOWN.wav'},{id:'S-6',title:'COMMUNITY FIRST',src:'/assets/audio/SYAYY/SYAYY - COMMUNITY FIRST.wav'},{id:'S-7',title:'FOR NOTHING BUT TRUTH',src:'/assets/audio/SYAYY/SYAYY - FOR NOTHING BUT TRUTH.wav'},{id:'S-8',title:'GREATEST CHARTIST',src:'/assets/audio/SYAYY/SYAYY - GREATEST CHARTIST.wav'},{id:'S-9',title:'SAY IT LOUD',src:'/assets/audio/SYAYY/SYAYY - SAY IT LOUD.wav'},{id:'S-10',title:'STEALTH LAUNCH DREAMS',src:'/assets/audio/SYAYY/SYAYY - STEALTH LAUNCH DREAMS.wav'}],
'YEVINCIBLE':[{id:'Y-1',title:'COMMUNITY MATTER',src:'/assets/audio/YEVINCIBLE/YEVINCIBLE - COMMUNITY MATTER (prod. stellarswagg).wav'},{id:'Y-2',title:'GET RIGHT FOR THE FUTURE',src:'/assets/audio/YEVINCIBLE/YEVINCIBLE - GET RIGHT FOR THE FUTURE.wav'},{id:'Y-3',title:'LOYALTY (OVER ROYALTY)',src:'/assets/audio/YEVINCIBLE/YEVINCIBLE - LOYALTY (over royalty).wav'},{id:'Y-4',title:'MANIFESTATION',src:'/assets/audio/YEVINCIBLE/YEVINCIBLE - MANIFESTATION (prod stellarswagg).wav'},{id:'Y-5',title:'PIXEEZUS',src:'/assets/audio/YEVINCIBLE/YEVINCIBLE - PIXEEZUS.wav'},{id:'Y-6',title:'RAISE YOUR HANDS',src:'/assets/audio/YEVINCIBLE/YEVINCIBLE - RAISE YOUR HANDS.wav'},{id:'Y-7',title:'VULTURES GET AWAY',src:'/assets/audio/YEVINCIBLE/YEVINCIBLE - VULTURES GET AWAY.wav'}],
'YURIM':[{id:'YU-1',title:'4NBT TIME',src:'/assets/audio/YURIM/4NBT TIME.mp3'},{id:'YU-2',title:'BEARS EVERYWHERE',src:'/assets/audio/YURIM/BEARS EVERYWHERE.mp3'},{id:'YU-3',title:"JOKER'S PLAN",src:"/assets/audio/YURIM/JOKER'S PLAN.mp3"},{id:'YU-4',title:'META',src:'/assets/audio/YURIM/MEta.mp3'},{id:'YU-5',title:'RACING TO THE FUTURE',src:'/assets/audio/YURIM/RACING TO THE FUTURE.mp3'}],
}
const MOST_STREAMED = []

function makeTex(sz=64,c=[1,1,1]){const cv=document.createElement('canvas');cv.width=cv.height=sz;const x=cv.getContext('2d'),g=x.createRadialGradient(sz/2,sz/2,0,sz/2,sz/2,sz/2);g.addColorStop(0,`rgba(${c[0]*255|0},${c[1]*255|0},${c[2]*255|0},1)`);g.addColorStop(.12,`rgba(${c[0]*255|0},${c[1]*255|0},${c[2]*255|0},.8)`);g.addColorStop(.35,`rgba(${c[0]*200|0},${c[1]*200|0},${c[2]*200|0},.25)`);g.addColorStop(.65,`rgba(${c[0]*120|0},${c[1]*120|0},${c[2]*120|0},.06)`);g.addColorStop(1,'rgba(0,0,0,0)');x.fillStyle=g;x.fillRect(0,0,sz,sz);const t=new THREE.CanvasTexture(cv);t.needsUpdate=true;return t}

// LAYER 1: Star dust
function StarDust(){const ct=2000,ref=useRef(),tex=useMemo(()=>makeTex(32,[.7,.75,.9]),[]),pos=useMemo(()=>{const p=new Float32Array(ct*3);for(let i=0;i<ct;i++){const th=Math.random()*Math.PI*2,r=2+Math.random()*25;p[i*3]=Math.cos(th)*r;p[i*3+1]=(Math.random()-.5)*8;p[i*3+2]=Math.sin(th)*r}return p},[]);useFrame(({clock})=>{if(ref.current)ref.current.rotation.y=clock.getElapsedTime()*.003});return(<points ref={ref}><bufferGeometry><bufferAttribute attach="attributes-position" array={pos} count={ct} itemSize={3}/></bufferGeometry><pointsMaterial map={tex} size={.15} transparent opacity={.6} depthWrite={false} blending={THREE.AdditiveBlending} color="#8090b8" sizeAttenuation/></points>)}

// LAYER 2: Orbital particles in rings
function OrbitalParticles(){const ct=600,ref=useRef(),tex=useMemo(()=>makeTex(48,[.8,.85,1]),[]),data=useMemo(()=>{const p=new Float32Array(ct*3),m=[];for(let i=0;i<ct;i++){const ring=Math.floor(Math.random()*5),br=1.5+ring*1.4,a=Math.random()*Math.PI*2,r=br+(Math.random()-.5)*.8,y=(Math.random()-.5)*.6;p[i*3]=Math.cos(a)*r;p[i*3+1]=y;p[i*3+2]=Math.sin(a)*r;m.push({a,r,y,s:.015+Math.random()*.025,ring})}return{p,m}},[]);useFrame(({clock})=>{if(!ref.current)return;const t=clock.getElapsedTime(),arr=ref.current.geometry.attributes.position.array;for(let i=0;i<ct;i++){const m=data.m[i],a=m.a+t*m.s*(m.ring%2===0?1:-1);arr[i*3]=Math.cos(a)*m.r;arr[i*3+1]=m.y+Math.sin(t*.5+i)*.05;arr[i*3+2]=Math.sin(a)*m.r}ref.current.geometry.attributes.position.needsUpdate=true});return(<points ref={ref}><bufferGeometry><bufferAttribute attach="attributes-position" array={data.p} count={ct} itemSize={3}/></bufferGeometry><pointsMaterial map={tex} size={.22} transparent opacity={.7} depthWrite={false} blending={THREE.AdditiveBlending} color="#a0b0d0" sizeAttenuation/></points>)}

// LAYER 3: Glowing spheres
const SPHERES=(()=>{const s=[];let id=0;for(let arm=0;arm<2;arm++){const off=arm*Math.PI;for(let i=0;i<12;i++){const t=i/12,a=off+t*Math.PI*2.5,r=1+t*5,f=arm===0&&i>=7;s.push({id:id++,a,r,sz:f?.35+Math.random()*.3:.08+Math.random()*.18,sp:.04+Math.random()*.03,f})}}for(let i=0;i<12;i++)s.push({id:id++,a:Math.random()*Math.PI*2,r:Math.random()*1.2,sz:.04+Math.random()*.1,sp:.08+Math.random()*.06,f:false});return s})()

const haloTex=makeTex(64,[.6,.65,.8])
function GlowSphere({d,onClick}){const ref=useRef(),[h,setH]=useState(false);useFrame(({clock})=>{if(!ref.current)return;const t=clock.getElapsedTime()*d.sp;ref.current.position.set(Math.cos(d.a+t)*d.r,Math.sin(t*.3+d.id*.5)*.1,Math.sin(d.a+t)*d.r)});return(<group ref={ref}><mesh onClick={d.f?(e)=>{e.stopPropagation();onClick()}:undefined} onPointerOver={d.f?()=>{setH(true);document.body.style.cursor='pointer'}:undefined} onPointerOut={d.f?()=>{setH(false);document.body.style.cursor='default'}:undefined}><sphereGeometry args={[d.sz,d.f?48:16,d.f?48:16]}/><meshStandardMaterial color={d.f?'#c0c8e0':'#8890a8'} metalness={.95} roughness={d.f?.05:.15} envMapIntensity={d.f?3:1.5} emissive={h?'#4060c0':d.f?'#1a2850':'#060a18'} emissiveIntensity={h?3:d.f?.6:.1}/></mesh>{d.sz>.12&&<sprite scale={[d.sz*5,d.sz*5,1]} raycast={()=>null}><spriteMaterial map={haloTex} transparent opacity={d.f?.15:.06} blending={THREE.AdditiveBlending} depthWrite={false}/></sprite>}</group>)}

// Energy lines
function EnergyLines(){const ref=useRef(),matRef=useRef();useFrame(({clock})=>{if(!ref.current)return;const t=clock.getElapsedTime();if(matRef.current)matRef.current.opacity=.04+Math.sin(t*.3)*.02;const pos=[];for(let i=0;i<SPHERES.length;i++){const a=SPHERES[i],at=t*a.sp,ax=Math.cos(a.a+at)*a.r,az=Math.sin(a.a+at)*a.r;for(let j=i+1;j<SPHERES.length;j++){const b=SPHERES[j],bt=t*b.sp,bx=Math.cos(b.a+bt)*b.r,bz=Math.sin(b.a+bt)*b.r;if(Math.sqrt((ax-bx)**2+(az-bz)**2)<2){pos.push(ax,Math.sin(t*.3+a.id*.5)*.1,az,bx,Math.sin(t*.3+b.id*.5)*.1,bz)}}}ref.current.geometry.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));ref.current.geometry.attributes.position.needsUpdate=true});return(<lineSegments ref={ref}><bufferGeometry/><lineBasicMaterial ref={matRef} color="#4a5880" transparent opacity={.05} blending={THREE.AdditiveBlending} depthWrite={false}/></lineSegments>)}

// Nebula + core
function Nebula(){const clouds=useMemo(()=>Array.from({length:8},()=>({p:[(Math.random()-.5)*6,(Math.random()-.5)*1.5,(Math.random()-.5)*6],s:3+Math.random()*5,o:.012+Math.random()*.018})),[]),tex=useMemo(()=>makeTex(128,[.4,.45,.6]),[]),coreTex=useMemo(()=>makeTex(128,[.8,.85,1]),[]),coreRef=useRef();useFrame(({clock})=>{if(coreRef.current){const p=1+Math.sin(clock.getElapsedTime()*.5)*.1;coreRef.current.scale.set(3*p,3*p,1)}});return(<>{clouds.map((c,i)=><sprite key={i} position={c.p} scale={[c.s,c.s,1]}><spriteMaterial map={tex} transparent opacity={c.o} blending={THREE.AdditiveBlending} depthWrite={false} color="#5060a0"/></sprite>)}<sprite ref={coreRef} position={[0,0,0]} scale={[3,3,1]}><spriteMaterial map={coreTex} transparent opacity={.12} blending={THREE.AdditiveBlending} depthWrite={false} color="#7888c0"/></sprite><sprite position={[0,.1,0]} scale={[5,5,1]}><spriteMaterial map={coreTex} transparent opacity={.06} blending={THREE.AdditiveBlending} depthWrite={false} color="#c0c8e0"/></sprite><sprite position={[0,-.05,0]} scale={[8,8,1]}><spriteMaterial map={coreTex} transparent opacity={.025} blending={THREE.AdditiveBlending} depthWrite={false} color="#d0d4e8"/></sprite><sprite position={[.3,.05,-.2]} scale={[3,3,1]}><spriteMaterial map={coreTex} transparent opacity={.035} blending={THREE.AdditiveBlending} depthWrite={false} color="#b8c0d8"/></sprite><sprite position={[-.4,.05,.3]} scale={[2.5,2.5,1]}><spriteMaterial map={coreTex} transparent opacity={.03} blending={THREE.AdditiveBlending} depthWrite={false} color="#a8b0c8"/></sprite></>)}

const CosmicScene=memo(function CosmicScene({onOrbClick}){return(<><color attach="background" args={['#020115']}/><fog attach="fog" args={['#020115',10,22]}/><ambientLight intensity={.12} color="#4050a0"/><pointLight position={[0,4,0]} intensity={4} color="#8090c0" distance={18} decay={2}/><pointLight position={[0,1,0]} intensity={2} color="#c0c8e0" distance={6} decay={2}/><pointLight position={[0,0.5,0]} intensity={1.2} color="#e0e4f0" distance={3} decay={1.5}/><pointLight position={[5,3,5]} intensity={1.5} color="#6878b0" distance={14} decay={2}/><pointLight position={[-5,2,-5]} intensity={1} color="#5868a8" distance={12} decay={2}/><Environment preset="night"/><Stars radius={80} depth={60} count={4000} factor={4} saturation={0} fade speed={.3}/><StarDust/><Nebula/><OrbitalParticles/><EnergyLines/>{SPHERES.map(s=><GlowSphere key={s.id} d={s} onClick={onOrbClick}/>)}<EffectComposer><Bloom intensity={1.8} luminanceThreshold={.1} luminanceSmoothing={.95} radius={.85} mipmapBlur/><Vignette eskil={false} offset={.1} darkness={.8} blendFunction={BlendFunction.NORMAL}/></EffectComposer></>)})

// ═══ UI ═══
function CATicker(){const items=Array.from({length:12},(_,i)=><a key={i} href={DEX_URL} target="_blank" rel="noopener noreferrer">{CA}</a>);return(<><div className="ca-ticker ca-top"><div className="ca-inner">{items}</div></div><div className="ca-ticker ca-bottom"><div className="ca-inner">{items}</div></div><div className="ca-ticker ca-right"><div className="ca-inner">{items}</div></div><div className="ca-ticker ca-left"><div className="ca-inner">{items}</div></div></>)}
function Clock(){const[time,setTime]=useState('');useEffect(()=>{const t=()=>{const n=new Date();setTime(`${String(n.getHours()).padStart(2,'0')}:${String(n.getMinutes()).padStart(2,'0')}:${String(n.getSeconds()).padStart(2,'0')}`)};t();const id=setInterval(t,1000);return()=>clearInterval(id)},[]);return <span className="font-mono text-3xl font-light tracking-[0.15em] opacity-35">{time}</span>}
function MostStreamedPanel(){return(<div className="glass p-5" style={{minWidth:300}}><h3 className="font-display text-xl tracking-wide mb-4 opacity-80">MOST STREAMED MUSIC</h3><div className="space-y-2.5">{MOST_STREAMED.map(item=>(<div key={item.rank} className="flex items-center justify-between font-mono text-[10px] font-light opacity-55 hover:opacity-80 transition-opacity cursor-default"><span className="truncate">{item.artist} - {item.title}</span><span className="ml-6 tabular-nums flex-shrink-0">{item.streams}</span></div>))}</div></div>)}
function ArtistFolder({selectedArtist,onSelectArtist,onBack,currentTrack,onPlayTrack}){const [anim,setAnim]=useState('');useEffect(()=>{setAnim('animate-in');const t=setTimeout(()=>setAnim(''),400);return()=>clearTimeout(t)},[selectedArtist]);if(selectedArtist){const tracks=ARTIST_TRACKS[selectedArtist]||[];return(<div className={`glass folder-static ${anim}`} style={{width:280}}><div className="flex items-center gap-2 px-4 py-3 border-b border-white/5"><button onClick={onBack} className="ctrl-btn"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"><path d="M19 12H5M12 19l-7-7 7-7"/></svg></button><span className="font-mono text-xs font-medium tracking-wider uppercase">{selectedArtist}</span></div><div className="p-2 space-y-0.5 overflow-y-auto" style={{maxHeight:'calc(100% - 44px)'}}>{tracks.map(track=>(<div key={track.id} className={`track-row flex items-center justify-between ${currentTrack?.id===track.id?'active':''}`} onClick={()=>onPlayTrack(track,selectedArtist)}><span className="font-mono font-light truncate">{track.title}</span></div>))}</div></div>)}return(<div className={`glass p-3 folder-static ${anim}`} style={{width:280}}><div className="grid grid-cols-2 gap-2">{ARTISTS.map(name=><button key={name} className="artist-btn" onClick={()=>onSelectArtist(name)}>{name}</button>)}</div></div>)}
function VolumeIcon({volume}){if(volume===0)return <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" className="opacity-35"><polygon points="11 5 6 9 2 9 2 15 6 15 11 19 11 5"/><line x1="23" y1="9" x2="17" y2="15"/><line x1="17" y1="9" x2="23" y2="15"/></svg>;return <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" className="opacity-35"><polygon points="11 5 6 9 2 9 2 15 6 15 11 19 11 5"/>{volume>0&&<path d="M15.54 8.46a5 5 0 010 7.07"/>}{volume>.5&&<path d="M19.07 4.93a10 10 0 010 14.14"/>}</svg>}
function RepeatIcon({mode}){return(<span className="relative inline-flex items-center justify-center"><svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"><polyline points="17 1 21 5 17 9"/><path d="M3 11V9a4 4 0 014-4h14"/><polyline points="7 23 3 19 7 15"/><path d="M21 13v2a4 4 0 01-4 4H3"/></svg>{mode===2&&<span className="absolute -top-1.5 -right-2 font-mono text-[8px] font-bold">1</span>}</span>)}
function formatTime(s){if(!s||isNaN(s))return'0:00';return Math.floor(s/60)+':'+String(Math.floor(s%60)).padStart(2,'0')}
function PlayerBar({currentTrack,currentArtist,isPlaying,progress,duration,volume,shuffle,repeatMode,onPlayPause,onPrev,onNext,onSeek,onVolumeChange,onToggleShuffle,onCycleRepeat}){const handleSeek=(e)=>{const r=e.currentTarget.getBoundingClientRect();onSeek(((e.clientX-r.left)/r.width)*duration)};return(<div className="player-bar-wrap"><div className="player-bar px-4 py-1.5"><div className="flex items-center gap-3"><div className="flex-1 min-w-0 hidden sm:block">{currentTrack?(<div><p className="font-mono text-[10px] font-light truncate opacity-40">{currentArtist}</p><p className="font-mono text-[11px] font-light truncate opacity-65">{currentTrack.title}</p></div>):(<p className="font-mono text-[11px] font-light truncate opacity-40">No track selected</p>)}</div><div className="flex items-center gap-1"><button className="ctrl-btn" onClick={onPrev}><svg width="14" height="14" viewBox="0 0 24 24" fill="currentColor"><path d="M6 6h2v12H6zm3.5 6l8.5 6V6z"/></svg></button><button className="ctrl-btn" onClick={onPlayPause}>{isPlaying?<svg width="18" height="18" viewBox="0 0 24 24" fill="currentColor"><rect x="6" y="4" width="4" height="16"/><rect x="14" y="4" width="4" height="16"/></svg>:<svg width="18" height="18" viewBox="0 0 24 24" fill="currentColor"><path d="M8 5v14l11-7z"/></svg>}</button><button className="ctrl-btn" onClick={onNext}><svg width="14" height="14" viewBox="0 0 24 24" fill="currentColor"><path d="M6 18l8.5-6L6 6v12zM16 6v12h2V6h-2z"/></svg></button></div><div className="flex-[2] min-w-[80px] hidden sm:block"><div className="progress-track" onClick={handleSeek}><div className="progress-fill" style={{width:`${duration?(progress/duration)*100:0}%`}}/></div></div><div className="hidden sm:flex items-center gap-1"><span className="font-mono text-[10px] opacity-25">{formatTime(progress)}</span><span className="font-mono text-[10px] opacity-12">/</span><span className="font-mono text-[10px] opacity-25">{formatTime(duration)}</span></div><div className="hidden md:flex vol-wrap"><VolumeIcon volume={volume}/><input type="range" className="vol-slider" min="0" max="1" step="0.05" value={volume} onChange={e=>onVolumeChange(parseFloat(e.target.value))} style={{'--vol-pct':`${Math.round(volume*100)}%`}}/></div><button className={`ctrl-btn hidden sm:flex ${shuffle?'active':''}`} onClick={onToggleShuffle}><svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"><polyline points="16 3 21 3 21 8"/><line x1="4" y1="20" x2="21" y2="3"/><polyline points="21 16 21 21 16 21"/><line x1="15" y1="15" x2="21" y2="21"/><line x1="4" y1="4" x2="9" y2="9"/></svg></button><button className={`ctrl-btn hidden sm:flex ${repeatMode>0?'active':''}`} onClick={onCycleRepeat}><RepeatIcon mode={repeatMode}/></button></div></div></div>)}
function MobileStreamedButton({expanded,onToggle}){return(<div><button onClick={onToggle} className="glass w-full px-4 py-2.5 flex items-center justify-between"><span className="font-mono text-[10px] font-medium tracking-wider uppercase opacity-60">Most Streamed Music</span><svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" className={`opacity-30 transition-transform duration-200 ${expanded?'rotate-180':''}`}><polyline points="6 9 12 15 18 9"/></svg></button>{expanded&&<div className="glass mt-1 p-3 space-y-1.5">{MOST_STREAMED.map(item=><div key={item.rank} className="flex justify-between font-mono text-[9px] font-light opacity-50"><span className="truncate">{item.artist} - {item.title}</span><span className="tabular-nums ml-2 flex-shrink-0">{item.streams}</span></div>)}</div>}</div>)}

export default function App(){
  const[selectedArtist,setSelectedArtist]=useState(null),[currentTrack,setCurrentTrack]=useState(null),[currentArtist,setCurrentArtist]=useState(null),[isPlaying,setIsPlaying]=useState(false),[progress,setProgress]=useState(0),[duration,setDuration]=useState(0),[volume,setVolume]=useState(.8),[shuffle,setShuffle]=useState(false),[repeatMode,setRepeatMode]=useState(0),[mobileStreamed,setMobileStreamed]=useState(false),[isMobile,setIsMobile]=useState(false)
  const audioRef=useRef(new Audio())
  useEffect(()=>{const c=()=>setIsMobile(window.innerWidth<=768);c();window.addEventListener('resize',c);return()=>window.removeEventListener('resize',c)},[])
  useEffect(()=>{const a=audioRef.current;a.volume=volume;const onT=()=>setProgress(a.currentTime),onM=()=>setDuration(a.duration),onE=()=>{if(repeatMode===2){a.currentTime=0;a.play()}else handleNext()};a.addEventListener('timeupdate',onT);a.addEventListener('loadedmetadata',onM);a.addEventListener('ended',onE);return()=>{a.removeEventListener('timeupdate',onT);a.removeEventListener('loadedmetadata',onM);a.removeEventListener('ended',onE)}},[repeatMode])
  useEffect(()=>{audioRef.current.volume=volume},[volume])
  const handlePlayTrack=useCallback((track,artist)=>{const a=audioRef.current;if(currentTrack?.id===track.id){if(isPlaying){a.pause();setIsPlaying(false)}else{a.play().catch(()=>{});setIsPlaying(true)};return};if(track.src){a.src=withAudioBase(track.src);a.play().catch(()=>{})};setCurrentTrack(track);setCurrentArtist(artist);setIsPlaying(true)},[currentTrack,isPlaying])
  const handlePlayPause=useCallback(()=>{if(!currentTrack)return;if(isPlaying){audioRef.current.pause();setIsPlaying(false)}else{audioRef.current.play().catch(()=>{});setIsPlaying(true)}},[currentTrack,isPlaying])
  const handleNext=useCallback(()=>{if(!currentArtist)return;if(shuffle){const allTracks=[];ARTISTS.forEach(a=>{(ARTIST_TRACKS[a]||[]).forEach(t=>allTracks.push({track:t,artist:a}))});const pick=allTracks[Math.floor(Math.random()*allTracks.length)];setSelectedArtist(pick.artist);handlePlayTrack(pick.track,pick.artist)}else if(repeatMode===1){const t=ARTIST_TRACKS[currentArtist]||[],idx=t.findIndex(x=>x.id===currentTrack?.id);handlePlayTrack(t[(idx+1)%t.length],currentArtist)}else{const t=ARTIST_TRACKS[currentArtist]||[],idx=t.findIndex(x=>x.id===currentTrack?.id);if(idx<t.length-1){handlePlayTrack(t[idx+1],currentArtist)}else{const ai=ARTISTS.indexOf(currentArtist);const nextArtist=ARTISTS[(ai+1)%ARTISTS.length];const nt=ARTIST_TRACKS[nextArtist]||[];if(nt.length){setSelectedArtist(nextArtist);handlePlayTrack(nt[0],nextArtist)}}}},[currentArtist,currentTrack,shuffle,repeatMode,handlePlayTrack])
  const handlePrev=useCallback(()=>{if(!currentArtist)return;const t=ARTIST_TRACKS[currentArtist]||[],idx=t.findIndex(x=>x.id===currentTrack?.id);if(progress>3){audioRef.current.currentTime=0;setProgress(0);return};handlePlayTrack(t[idx<=0?t.length-1:idx-1],currentArtist)},[currentArtist,currentTrack,progress,handlePlayTrack])
  const handleSeek=useCallback((time)=>{audioRef.current.currentTime=time;setProgress(time)},[])
  const handleOrbClick=useCallback(()=>{const artist=ARTISTS[Math.floor(Math.random()*ARTISTS.length)],tracks=ARTIST_TRACKS[artist],track=tracks[Math.floor(Math.random()*tracks.length)];setSelectedArtist(artist);handlePlayTrack(track,artist)},[handlePlayTrack])
  const pp={currentTrack,currentArtist,isPlaying,progress,duration,volume,shuffle,repeatMode,onPlayPause:handlePlayPause,onPrev:handlePrev,onNext:handleNext,onSeek:handleSeek,onVolumeChange:setVolume,onToggleShuffle:()=>setShuffle(p=>!p),onCycleRepeat:()=>setRepeatMode(p=>(p+1)%3)}
  return(<>
    <Canvas className="r3f-bg" camera={{position:[0,9,5],fov:55}} dpr={[1,1.5]} gl={{antialias:true,alpha:false,powerPreference:'high-performance'}} onCreated={({camera})=>{camera.lookAt(0,0,0)}}><CosmicScene onOrbClick={handleOrbClick}/></Canvas>
    <div className="grain"/><CATicker/>
    <div className="app-container">{isMobile?(<><div className="text-center pt-2 pb-1"><h1 className="font-display text-3xl tracking-wide leading-none">THE CRYPTO DROPOUT</h1><p className="font-mono text-[9px] font-light tracking-[0.25em] mt-1 opacity-40">COMMUNITY LEGACY</p></div>{MOST_STREAMED.length>0&&<MobileStreamedButton expanded={mobileStreamed} onToggle={()=>setMobileStreamed(p=>!p)}/>}<div className="flex-1 min-h-0 mt-1 overflow-y-auto"><ArtistFolder selectedArtist={selectedArtist} onSelectArtist={setSelectedArtist} onBack={()=>setSelectedArtist(null)} currentTrack={currentTrack} onPlayTrack={handlePlayTrack}/></div><div className="mt-1"><PlayerBar {...pp}/></div></>):(<><div className="main-area"><div className="title-area"><h1 className="font-display text-5xl lg:text-6xl xl:text-7xl tracking-wide leading-[0.88]">THE CRYPTO DROPOUT</h1><p className="font-mono text-[11px] font-light tracking-[0.25em] mt-2 opacity-35">COMMUNITY LEGACY</p></div><div className="streamed-area">{MOST_STREAMED.length>0&&<MostStreamedPanel/>}</div><div className="folder-area"><ArtistFolder selectedArtist={selectedArtist} onSelectArtist={setSelectedArtist} onBack={()=>setSelectedArtist(null)} currentTrack={currentTrack} onPlayTrack={handlePlayTrack}/></div><div className="clock-area"><Clock/></div></div><PlayerBar {...pp}/></>)}</div>
  </>)
}
